



urls = [

    "https://www.jumbo.com.ar/almacen/aceites-y-vinagres",
    "https://www.jumbo.com.ar/almacen/aderezos",
    "https://www.jumbo.com.ar/almacen/arroz-y-legumbres",
    "https://www.jumbo.com.ar/almacen/caldos-sopas-pure-y-bolsas-para-horno",
    "https://www.jumbo.com.ar/almacen/conservas",
    "https://www.jumbo.com.ar/almacen/desayuno-y-merienda",
    "https://www.jumbo.com.ar/almacen/golosinas-y-chocolates",
    "https://www.jumbo.com.ar/almacen/harinas",
    "https://www.jumbo.com.ar/almacen/importados",
    "https://www.jumbo.com.ar/almacen/panificados",
    "https://www.jumbo.com.ar/almacen/panificados",
    "jumbo.com.ar/almacen/para-preparar",
    "https://www.jumbo.com.ar/almacen/pastas-secas-y-salsas",
    "https://www.jumbo.com.ar/almacen/sal-pimienta-y-especias",
    "https://www.jumbo.com.ar/bebidas/a-base-de-hierbas",
    "https://www.jumbo.com.ar/bebidas/aguas",
    "https://www.jumbo.com.ar/bebidas/aperitivos",
    "https://www.jumbo.com.ar/bebidas/bebidas-blancas",
    "https://www.jumbo.com.ar/bebidas/cervezas",
    "https://www.jumbo.com.ar/bebidas/champagnes",
    "https://www.jumbo.com.ar/bebidas/gaseosas",
    "https://www.jumbo.com.ar/bebidas/generosos",
    "https://www.jumbo.com.ar/bebidas/hielo",
    "https://www.jumbo.com.ar/bebidas/isotonicas",
    "https://www.jumbo.com.ar/bebidas/jugos",
    "https://www.jumbo.com.ar/bebidas/licores",
    "https://www.jumbo.com.ar/bebidas/sidras",
    "https://www.jumbo.com.ar/bebidas/vinos",
    "https://www.jumbo.com.ar/bebidas/whiskys",
    "https://www.jumbo.com.ar/frutas-y-verduras/frutas",
    "https://www.jumbo.com.ar/frutas-y-verduras/hierbas-aromaticas-y-plantines",
    "https://www.jumbo.com.ar/frutas-y-verduras/huevos",
    "https://www.jumbo.com.ar/frutas-y-verduras/legumbres-granos-y-semillas",
    "https://www.jumbo.com.ar/frutas-y-verduras/organicos",
    "https://www.jumbo.com.ar/frutas-y-verduras/verduras",
    "https://www.jumbo.com.ar/carnes/pollos",
    "https://www.jumbo.com.ar/carnes/menudencias",
    "https://www.jumbo.com.ar/carnes/listos-para-cocinar",
    "https://www.jumbo.com.ar/carnes/embutidos",
    "https://www.jumbo.com.ar/carnes/cordero-lechon-chivito-y-conejo",
    "https://www.jumbo.com.ar/carnes/carne-de-cerdo",
    "https://www.jumbo.com.ar/carnes/carne-vacuna",
    "https://www.jumbo.com.ar/carnes/carbon-y-lena",
    "https://www.jumbo.com.ar/bebes-y-ninos/panales",
    "https://www.jumbo.com.ar/bebes-y-ninos/mamaderas-chupetes-y-baberos",### PROBLEMA PAGINA deprecada o rota desde el server
    "https://www.jumbo.com.ar/bebes-y-ninos/alimentacion", #### PROBLEMAS PAGINA
    "https://www.jumbo.com.ar/bebes-y-ninos/cuidado-del-bebe",
    "https://www.jumbo.com.ar/pescados-y-mariscos/mariscos",
    "https://www.jumbo.com.ar/pescados-y-mariscos/pescados",
    "https://www.jumbo.com.ar/quesos-y-fiambres/dulces",
    "https://www.jumbo.com.ar/quesos-y-fiambres/encurtidos-aceitunas-y-pickles",
    "https://www.jumbo.com.ar/quesos-y-fiambres/fiambres",
    "https://www.jumbo.com.ar/quesos-y-fiambres/quesos",
    "https://www.jumbo.com.ar/quesos-y-fiambres/salchichas",
    "https://www.jumbo.com.ar/lacteos/cremas",
    "https://www.jumbo.com.ar/lacteos/dulce-de-leche",
    "https://www.jumbo.com.ar/lacteos/leches",
    "https://www.jumbo.com.ar/lacteos/mantecas-y-margarinas",
    "https://www.jumbo.com.ar/lacteos/pastas-frescas-y-tapas",
    "https://www.jumbo.com.ar/lacteos/postres",
    "https://www.jumbo.com.ar/lacteos/yogures",
    "https://www.jumbo.com.ar/congelados/vegetales",
    "https://www.jumbo.com.ar/congelados/pollo-y-carnes",
    "https://www.jumbo.com.ar/congelados/comidas-congeladas",
    "https://www.jumbo.com.ar/congelados/frutas",
    "https://www.jumbo.com.ar/congelados/hamburguesas-y-milanesas",
    "https://www.jumbo.com.ar/congelados/helados-y-postres",
    "https://www.jumbo.com.ar/congelados/panaderia",### problema pagina no carga
    "https://www.jumbo.com.ar/congelados/papas",
    "https://www.jumbo.com.ar/congelados/pescados-y-mariscos",
    "https://www.jumbo.com.ar/panaderia-y-reposteria/reposteria",
    "https://www.jumbo.com.ar/panaderia-y-reposteria/panaderia",
    "https://www.jumbo.com.ar/perfumeria/cuidado-capilar",
    "https://www.jumbo.com.ar/perfumeria/cuidado-oral",
    "https://www.jumbo.com.ar/perfumeria/cuidado-personal",
    "https://www.jumbo.com.ar/perfumeria/cuidado-de-la-piel",
    "https://www.jumbo.com.ar/perfumeria/farmacia",
    "https://www.jumbo.com.ar/limpieza/accesorios-de-limpieza",
    "https://www.jumbo.com.ar/limpieza/calzado",
    "https://www.jumbo.com.ar/limpieza/cuidado-para-la-ropa",
    "https://www.jumbo.com.ar/limpieza/desodorantes-de-ambiente",
    "https://www.jumbo.com.ar/limpieza/insecticidas",
    "https://www.jumbo.com.ar/limpieza/lavandina    ",
    "https://www.jumbo.com.ar/limpieza/limpieza-de-bano",
    "https://www.jumbo.com.ar/limpieza/limpieza-de-cocina",
    "https://www.jumbo.com.ar/limpieza/limpieza-de-pisos-y-muebles",
    "https://www.jumbo.com.ar/limpieza/papeles",
    "https://www.jumbo.com.ar/mascotas/perros",
    "https://www.jumbo.com.ar/mascotas/gatos",
    "https://www.jumbo.com.ar/mascotas/accesorios-para-mascotas",
]